### ISSUE TITLE
Fix documentation

### ISSUE THREAD

**Issue by NathanGrimaud** [sylvainDNS/back-redis-locator#4]
Socket handshake parameter sample :
`{"query": "params={\"uuid\":\"f65eebe2-aa4d-4fe5-80f4-0026e4cc47f7\", \"username\":\"dns\", \"long\":\"50\", \"lat\":\"50\", \"radius\":\"2\"}"}`

I think that we should remove the `uuid` param as we don't need it anymore

**Comment by sylvainDNS** [comment]
Fixed https://github.com/sylvainDNS/back-redis-locator/commit/de29d773ec39f3f49dc160da32cc57c721505534
